### ISSUE TITLE
Add PropTypes to all the things

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#114]
Ok, lets add in propTypes for all the things

```js
Icon.propTypes = {
  icon: PropTypes.string.isRequired,
  color: PropTypes.func.isRequired,  
  size: PropTypes.number,
  viewbox: PropTypes.string
}
```

## Components
- [x] BearsTeam.js 
- [x] Button.js
- [x] CardContainer.js
- [x] Divider.js
- [x] Footer.js
- [x] Header.js
- [x] Hero.js
- [x] Icon.js
- [x] JobsList.js
- [x] PageNav.js
- [x] Pagination.js
- [x] ProjectCard.js
- [x] Quote.js
- [x] StoreyCard.js

## Pages
- [x] events.js
- [x] index.js
- [x] jobs.js
- [x] learn.js
- [x] stories.js
- [x] support.js

**Comment by mar-bi** [comment]
I'm going to check it with `eslint` first.
It have to do something good despite its behavior with `gatsby` :smile:

**Comment by mar-bi** [comment]
I checked only components, that have already had `prop-types` or don't need.

**Comment by mar-bi** [comment]
I fixed `prop-types` for:
 - BearsTeam.js
 - Button.js
 - CardContainer.js
 - Divider.js
 - PageNav.js 
 - ProjectCard.js

**Comment by spences10** [comment]
Ok, so there's:

* JobsList.js
* Quote.js
* events.js
* index.js
* jobs.js
* learn.js
* stories.js
* support.js

I'll take a look now

**Comment by spences10** [comment]
Ok, PR incomming
