### ISSUE TITLE
ESLint linebreak style

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#118]
I feared this would happen,

###### when I say 'this' I mean ESLint wasting my time 🙃 

![image](https://user-images.githubusercontent.com/234708/34242662-9606e44a-e614-11e7-9a4b-6210d162ed56.png)

Is the `linebreak-style` needed, I use Windows and have either had to use editor config 🐭  or not use ESLint 🙃 to get rid of this warning in the past.

I spent my morning trying to find a solution to an issue we didn't have before introducing ESLint.

**Comment by spences10** [comment]
This solves a lot of my issues:

![image](https://user-images.githubusercontent.com/234708/34243333-23aa2250-e618-11e7-963e-4c9b68bba723.png)

**Comment by mar-bi** [comment]
I can't say that I don't like `eslint`.
However, I'm not happy to get the errors about undefined `theme` props or undefined `graphql`. :angry: 
Ok, there are solutions, like importing `graphql`. But shall I do that if it works without import? 

Also we switched from importing the `ColorPalette` in every component to the `Theme`. Now I `eslint` pushes me to declare the usage of the  `theme` in props of every component which I'd like to colour.  
It's going crazy.  :angry:
I have one more issue where `eslint` doesn't like the indentation of a component but `prettier` finds it very legal. :thinking: 

Besides that, `eslint` has lots of pros. :upside_down_face: 

**My conclusion:**  I can continue using it, but accepting that it has a constant of errors in stuff we have got from `styled-components` and `gatsby` or `prettier` (like `theme`, `graphql`, indentation) .

**Comment by spences10** [comment]
I've edited my dotfiles [I'm Windows and Ubuntu user via Windows Subsystem Linux so two `.giotconfig`'s] I was going to make a patch PR but after following [this] guide and branching all the line ending errors seem to have gone

[this]: https://help.github.com/articles/dealing-with-line-endings/

**Comment by mar-bi** [comment]
Here is my final thought about `eslint` with `gatsby` :upside_down_face: 
All this long story looks for me like the [Yack Shaving](http://sethgodin.typepad.com/seths_blog/2005/03/dont_shave_that.html) :ox: :scissors: 
And I'm not a good barber :upside_down_face:

**Comment by spences10** [comment]
Closing with reference to https://help.github.com/articles/dealing-with-line-endings/

From https://github.com/chingu-voyage3/grad.then/issues/118#issuecomment-353558527
