### ISSUE TITLE
Responsive app layout

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage3/grad.then#121]
It's time to make our app responsive.
We are going to do it with **CSS grid**.

I'd like to make some experiments first, because it involves rethinking all layouts. :thinking: 
(It was one of the reasons for creating this issue. I want to have a number for my branch :smiley: )

I'm going to present ideas here and initiate the discussion. :speaker:   

Divide it in parts:
1. **Components**

- [x] responsive **Nav**
- [x] responsive **Hero**
- [x] responsive **CardContainer** & **Cards**
- [x] responsive **Responsive Divider**
---
2. **Pages**

- [x] responsive **Main Page**
- [x] responsive **Jobs Page**
- [x] responsive **Learn Page**
- [x] responsive **Events Page**
- [x] responsive **Support Page**
- [x] responsive **Stories Page**
- [x] responsive **404 Page**

**Comment by spences10** [comment]
I found [this] really helpful

[this]: https://github.com/styled-components/styled-components/blob/master/docs/tips-and-tricks.md#more-powerful-example

**Comment by mar-bi** [comment]
Great idea, @spences10 . :+1: 

I'd like to use [media-templates](https://github.com/styled-components/styled-components/blob/master/docs/tips-and-tricks.md#media-templates).
**Main advantages**:
- we define a set of breakpoints once and use them through all pages
- breakpoints are in **em**s 

We add to `globalStyle.js`
```js
const sizes = {
  giant: 1170,
  desktop: 992,
  tablet: 768,
  phone: 376
}

// iterate through the sizes and create a media template
export const media = Object.keys(sizes).reduce((accumulator, label) => {
  // use em in breakpoints to work properly cross-browser and support users
  // changing their browsers font-size: https://zellwk.com/blog/media-query-units/
  const emSize = sizes[label] / 16
  accumulator[label] = (...args) => css`
    @media (max-width: ${emSize}em) {
      ${css(...args)}
    }
  `
  return accumulator
}, {})
```
then import and use in **Components** (here is `PageNav.js`)

```js
import { media } from '../../theme/globalStyle'

const NavMenu = StyledUl.extend`
  ...
  ${media.giant`
    grid-template-columns: repeat(5, auto);
    margin: 0.7rem;
  `}
  ${media.desktop`
    margin: 0.5rem;
  `}
`
```

**Comment by spences10** [comment]
Ok, super, it looks like a variation on what I linked I'll have this for reference
