### ISSUE TITLE
nav items borders

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#139]
Hi, 

I'd like to take a look at using

```css
border: 1px solid transparent
```

On the nav items instead of `box-shadow`

**Comment by mar-bi** [comment]
Good idea!
I took your **css-rule** and use it on `Jobs Page`. It works fine :+1:

**Comment by spences10** [comment]
There's some odd effects on the corners with box shadow so I'm hoping a solid border will look better
