### ISSUE TITLE
Responsive Support Page

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage3/grad.then#165]
Make **Support Page** responsive

**Comment by mar-bi** [comment]
Hey @spences10 !
How it is going?
Do you need any help with it? :upside_down_face:

**Comment by spences10** [comment]
I think, most of the work has been done with this already @mar-bi 

I haven't done anything with it for a while but from looking at it last time there wasn't anything needed changing...

**Comment by mar-bi** [comment]
Well, I'm going to update the **Support** page. `Filter&Search` component needs to be added there.
After that it will be :100: done. :upside_down_face:

**Comment by spences10** [comment]
Ok, assign this to you then?

**Comment by mar-bi** [comment]
Yesssss :upside_down_face:
