### ISSUE TITLE
Rounded corners of rectangular containers & buttons

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage3/grad.then#185]
### Candies :candy:  for **Material UI** fans.

Started at https://github.com/chingu-voyage3/grad.then/issues/1#issuecomment-356289733 

Find, check and add
```.css
border-radius: 2px;
```
for all rectangular containers & buttons.

**Comment by spences10** [comment]
Ok, there were quite a few components I added with `border-radius: 4px;` so maybe we want to amend those too so everything is consistent 👌

**Comment by mar-bi** [comment]
Let's amend only components which have to look rectangular and keep rounded what is already rounded :upside_down_face: 
This will not cause changes to the design. It will make the rectangular stuff more **"Material"**.
A tiny piece of :hot_pepper:  
```.css
border-radius: 2px;
```
It works fine. :upside_down_face:
