### ISSUE TITLE
Real text for Main Page Hero

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage3/grad.then#186]
## Breathtaking and motivating phrases to `MainHero` of the **Main** Page
- 4 short phrases
- 3 - 4 words each
- to users of our app
- kindly convince them to use it :smile:

**Comment by spences10** [comment]
This is so not my thing

Lemme see if I can tap up someone on the Twittas

**Comment by mar-bi** [comment]
@spences10 , we can use your text from the `README` if you don't mind. :upside_down_face: 

- Completed your boot camp? 
- Collected all freeCodeCamp certificates?
- Finished a job-ready guide?
- No more challenges to take?

And the explanatory `<p>` after the title **"EXPLORE WHAT IS NEXT"**
_grad.then() gives you the information and tools you need to get a job after completing your training_

**Comment by mar-bi** [comment]
![screenshot-2018-1-16 grad then](https://user-images.githubusercontent.com/25195616/34994661-eef9ff06-fadc-11e7-88cd-53f724c24931.png)

**Comment by spences10** [comment]
Awesome, yes 👌

**Comment by mar-bi** [comment]
Great! :upside_down_face:
Let's have it on the **Main** page
