### ISSUE TITLE
404Page is not mounted correctly

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage3/grad.then#187]
## 404Page is not mounted correctly:
- https://chingu-voyage3.github.io/grad.then/somepage - it mounted first then disappears
- https://chingu-voyage3.github.io/grad.then/404 - correct

It looks like at the first route and extra layout (`index.js`) is loaded and shades the `NotFoundPage` layout.

Till now I haven't find a solution. :sos:

**Comment by spences10** [comment]
`ComponentWillMount` `ComponentDidMount`??

**Comment by spences10** [comment]
I'm trying to recreate this in development and it shows the Gatsby 404#
![image](https://user-images.githubusercontent.com/234708/34913712-e5cd663e-f8fc-11e7-83fb-efd6ff4499bb.png)

However from the GH page there's the following console output
![image](https://user-images.githubusercontent.com/234708/34913711-ddd51918-f8fc-11e7-8035-a50d2321687c.png)

I can't find a reference to the Hero component in the 404 page??

**Comment by mar-bi** [comment]
Exactly :nerd_face: 
The problem doesn't appear in "development mode". Only in a production version hosted on **gh-pages**.
For me it looks like a problem with page layouts - we have 2 separate layouts: `index` and `notFoundPage`. And we explicitly declared to use `notFoundPage` layout with **404**Page in `gatsby-node.js`.
```.js
exports.onCreatePage = ({ page, boundActionCreators }) => {
  const { createPage } = boundActionCreators

  return new Promise((resolve) => {
    if (page.path.match(/^\/404*/)) {
      page.layout = 'PageNotFound'
      createPage(page)
    }
    resolve()
  })
}
```
So when we hit:
 - **404page** at https://chingu-voyage3.github.io/grad.then/404
It loads only layout for 404 page

![screenshot from 2018-01-14 16-10-37](https://user-images.githubusercontent.com/25195616/34916942-2a5affbe-f948-11e7-9458-166cd01f53c1.png)


- any **dummy** route like https://chingu-voyage3.github.io/grad.then/abc
 and we get first **404** page then it loads the index page and the index layout as a top layer :worried: 

![screenshot from 2018-01-14 16-09-58](https://user-images.githubusercontent.com/25195616/34916934-15975aaa-f948-11e7-8e50-02c3e2f0d7bd.png)

**Comment by mar-bi** [comment]
>I can't find a reference to the Hero component in the 404 page??

`Hero` is from the `index.js` page :arrow_up:

**Comment by mar-bi** [comment]
Can we use `if - else if - else` instead of `if` and list explicitly all pages and  their layouts?
```.js
exports.onCreatePage = ({ page, boundActionCreators }) => {
  const { createPage } = boundActionCreators

  return new Promise((resolve) => {
    if (page.path.match(/^\/404*/)) {
      page.layout = 'PageNotFound'
      createPage(page)
    } else if (page.path.match(/^\/index/)){
      page.layout = 'index'
      createPage(page)  
    } else if (page.path.match(/^\/jobs/)){
      page.layout = 'index'
      createPage(page) 
   }
   ...
   else {
     page.layout = 'NotFoundPage'
     createPage(page) 
  }
    resolve()
  })
}
```

**Comment by spences10** [comment]
I saw [this] earlier and wasn't sure if it was relevant

[this]: https://spectrum.chat/?t=bc132d47-f267-4641-8a3e-33d4298c3410

**Comment by mar-bi** [comment]
After a period of thinking :thinking: and reading :desktop_computer:, I see 2 possible sources of the problem:
1.  https://github.com/chingu-voyage3/grad.then/issues/187#issuecomment-357521048 as @spences10 mentioned.
2. "layout conflict" - we fix the `PageNotFound` layout for *404* page only but not for any dummy page.
So it loads `index` layout.

I'm going to set a playground and try different tests:
1. give *404*  `index` layout see if it is mounted properly (`...\404` and  `...\dummy-route` should give the same results). This will exclude the first source.
2. list layouts for all pages https://github.com/chingu-voyage3/grad.then/issues/187#issuecomment-357521040 and check the results.

**Comment by mar-bi** [comment]
Results of **test 1**:
1. 404 route

![image](https://user-images.githubusercontent.com/25195616/34939627-269e9036-f9f5-11e7-9918-1d2778da1ff2.png)

2. dummy route

![image](https://user-images.githubusercontent.com/25195616/34939665-566bcb4e-f9f5-11e7-9011-7e6567dcbfc1.png)

**Conclusion:**
- 404 page mounted correctly with the index layout.
-  problem source number **1** is excluded. :woman_scientist:

P.S. I deployed the app to a github repo for testing purposes. I will delete it after I finish with this issue.

**Comment by mar-bi** [comment]
Results of **test 2**:
1.  404 route

![image](https://user-images.githubusercontent.com/25195616/34944875-e7c93d38-fa09-11e7-9d8b-a26db8428029.png)

2. dummy route 

![image](https://user-images.githubusercontent.com/25195616/34944918-13fca674-fa0a-11e7-813c-018f9a112911.png)

**Conclusion**:
- "explicit layout declaration" works :+1: 
- for every new **dummy** page `index` layout was applied previously (now `PageNotFound`)
- for every new **real** page we need to add layout declaration (which can be boring :thinking: )

Code in `gatsby-node.js`:
```.js
// test2: explicit layout declaration
...
    if (page.path.match(/^\/404*/)) {  //declare layout for 404 page
      page.layout = 'PageNotFound'
      createPage(page)
    } else if ( page.path.match(/^\//) || page.path.match(/^\/jobs/) ||
     page.path.match(/^\/learn/) || page.path.match(/^\/events/) ||
     page.path.match(/^\/support/) || page.path.match(/^\/stories/) ){ // declare layouts for all pages
      page.layout = 'index'
      createPage(page)
    } else { // this is the case for nonexistent pages
      page.layout = 'PageNotFound'
      createPage(page)
    }
...
```

**Comment by mar-bi** [comment]
So that, we have 2 possible solutions: :woman_scientist: :microscope: 
1. Turn to **one layout** for all pages (stick to `index` layout with the header and the footer) like in https://github.com/chingu-voyage3/grad.then/issues/187#issuecomment-357653790 + update the 404Page to look nice with the new layout.
2. Declare layouts for all pages and get the original 404Page (with pitfalls I mentioned previously )

**Comment by spences10** [comment]
1

**Comment by mar-bi** [comment]
I also prefer **1** due to its simplicity :+1:

**Comment by spences10** [comment]
super, do you know how many pages do not have the same layout?

**Comment by mar-bi** [comment]
if we stick to **1**,  we have only 1 layout for all pages - `index.js`
Before we used 2 layouts : 
- `index.js` for our 6 pages
- `PageNotFound` for 404 Page

**Comment by mar-bi** [comment]
Hooray!!! It works! :fireworks: :100: 

![image](https://user-images.githubusercontent.com/25195616/34993043-bc4f7b08-fad7-11e7-8e6e-f490a851d6a6.png)

I'm happy to close this issue! :smiley: :x:
