### ISSUE TITLE
update dependencies 

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#191]
I'm yak shaving!!

![image](https://user-images.githubusercontent.com/234708/34929502-2c3a15da-f9bc-11e7-9d45-c5a3f41cf320.png)

One thing to note here is that we need `react-helmet` installed `gatsby-plugin-react-helmet` when updated doesn't work without it.

I'd like to add `pretty-quick` and a `.prettierrc` file into the project too and also get a `travis.yml` so we can automate deploying to gh-pages

**Comment by mar-bi** [comment]
Nice new label ! :smile: :+1: 
Let's update `gatsby-helmet` together with `react-helmet`.
I like prettier, let's try `pretty-quick`. :lipstick:
And, for sure, we need to automate the deployment. :ok_hand:

**Comment by spences10** [comment]
Ok, we're done 😅 

![image](https://user-images.githubusercontent.com/234708/34931441-baba7eb2-f9c6-11e7-931b-1c1d2056ad98.png)

Going to finish up with a Travis CI pipeline 👍
