### ISSUE TITLE
Add Waffle.io Throughput Graph

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#20]
Add in some metrics badges to the project README.md

This is the Markdown for the badge:

```
[![Waffle.io - Columns and their card count](https://badge.waffle.io/chingu-voyage3/bears-16.svg?columns=all)](https://waffle.io/chingu-voyage3/bears-16) 
```

Will give you this shiny one:

[![Waffle.io - Columns and their card count](https://badge.waffle.io/chingu-voyage3/bears-16.svg?columns=all)](https://waffle.io/chingu-voyage3/bears-16) 

And this one will give you a nice burndown chart 🔥 :

```
[![Throughput Graph](https://graphs.waffle.io/chingu-voyage3/bears-16/throughput.svg)](https://waffle.io/chingu-voyage3/bears-16/metrics/throughput)
```

**SHINY:**

[![Throughput Graph](https://graphs.waffle.io/chingu-voyage3/bears-16/throughput.svg)](https://waffle.io/chingu-voyage3/bears-16/metrics/throughput)

**Comment by mar-bi** [comment]
I like them both. :+1: 
They are nice motivators. It would be easy for anyone to see how we are doing here. :rocket: :building_construction: :hammer: :wrench: 
I'd like to pick up it and play with these badges, of course, if you didn't mind. :smiley:

**Comment by spences10** [comment]
Absolutely, go ahead @mar-bi 👌 

Drop them into the top of the [README.md](https://github.com/chingu-voyage3/bears-16#gradthen)

**Comment by mar-bi** [comment]
What do you think about this? :smile: 
---
# grad.then()

[![Waffle.io - Columns and their card count](https://badge.waffle.io/chingu-voyage3/bears-16.svg?columns=all)](https://waffle.io/chingu-voyage3/bears-16)

## Chingu Voyage 3 project (bears-16 team)

### Life after freeCodeCamp

Completed your boot camp? No more freeCodeCamp challenges to take?

Looks like it's time to get a job! 💪

`grad.then()` is aimed at you, to give you the information and tools you need to
get a job after completing your training.

---

## Project Progress
We are proud to work as a team, and here is our **project progress**.  
We are *aspiring developers* and *eager learners*.
  
**And this is the very beginning.**

[![Throughput Graph](https://graphs.waffle.io/chingu-voyage3/bears-16/throughput.svg)](https://waffle.io/chingu-voyage3/bears-16/metrics/throughput)

**Comment by spences10** [comment]
Super duper! 🚀

**Comment by mar-bi** [comment]
I wanted it to be super motivating. :muscle:

**Comment by spences10** [comment]
Ok, so looks like there's one side effect of changing the project name

The URL needs changing on the readme for the waffle badge and graph @mar-bi 

Can I leave this with you?

![screenshot_20171213-181619](https://user-images.githubusercontent.com/234708/33954943-d625584c-e031-11e7-81c4-f929ceebe00a.jpg)

**Comment by mar-bi** [comment]
I saw it.
Sure. I will fix it now
