### ISSUE TITLE
Create reuseable components for pages

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#21]
We need to identify what components we can use on all the pages.

There will be 6 issues following this one where we can attempt to identify components to be created for each page.

They will all be going into a project for tracking  

## Checklist of components

**Check these off as they have issues created and added to the [Components](https://github.com/chingu-voyage3/bears-16/projects/3) project**

- [x] Nav
- [x] Story Card
- [x] Project Card
- [x] Buttons
- [x] Hero - big image
- [x] Divider component - [here][divider] for details
- [x] Icons - see #28 (comment) for details
- [x] Bear team logo component - to go in the nav
- [x] Search + filter
- [x] Pagination
- [x] Extended Filter
- [x] Jobs List
- [x] Cards container - see [here][cards-container]

[divider]: https://github.com/chingu-voyage3/bears-16/issues/26#issuecomment-351357710
[cards-container]: https://github.com/chingu-voyage3/grad.then/issues/24#issuecomment-351657965

**Comment by mar-bi** [comment]
As I wrote in #17 , for now I can distinguish 3 "reusables" through the all pages of the app:
1. `Header` with **app name** and app **navigation**
2. `Footer` with **navigation** and **team name**.
3. `PageNav` which serves slightly different styled navigation for `Header` and `Footer`. It can accomplish this task with *conditional styling*. 

Furthermore, there is a few more "reusables" sits on the next pages of the app:
  * `Dashbord` - a box with a page name right after the `Header` (all pages except **Main**)
  * `Dashbord Button` - (at **Events**, **Support**, **Stories**)
  * `Local nav menu with a search box` (all pages except **Main** and **Support**)
  * `Page Heading` like *FEATURED COURSES* - can be exported from `globalStyle.js`
  * A bunch of different **cards** and **lists** for a presentation of data got from API's.  It would be great, if we can make some of them reusable.

Which else do you detect? :mag: :male_detective:

**Comment by spences10** [comment]
I'm going to have to look at your awesome wireframes now to have a think about each one 🙃 

What if, on each of the items we have for the main pages we list out what we think is a component then we can move them all here and update the [main](https://github.com/chingu-voyage3/bears-16/issues/21#issue-281492659) post with them all for reference, sound good ❓

**Comment by mar-bi** [comment]
Sounds great! :+1: 
We are going to have an outstanding documentation. :upside_down_face:

**Comment by spences10** [comment]
It should help yes 😄

**Comment by asanhix** [comment]
I tick the divider maybe this article will help us to shape our own divider. https://shoutem.github.io/docs/ui-toolkit/components/dividers

**Comment by spences10** [comment]
This issue needs to be open still @asanhix  👍 

Up until we have all the items checked off

**Comment by asanhix** [comment]
@spences10 thanks :) I did see that `Close and comment` should be avoided and `Comment` is :+1

**Comment by spences10** [comment]
Ha yeah, we've all done it before in sure 😁

**Comment by mar-bi** [comment]
All 13 components have been added to **Components** Project. 
Congratulations, everybody!!! :fireworks: :boom: :boom:

**Comment by mar-bi** [comment]
All reusable components are done. :+1: :fireworks:

**Comment by spences10** [comment]
Shall we add this to the [App Design] milestone?

[App Design]: https://github.com/chingu-voyage3/grad.then/milestone/2

**Comment by mar-bi** [comment]
Yes, I think so. 
And mark that milestone as completed :smile:
