### ISSUE TITLE
Break Main page into components

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#22]
# discussion piece

![image](https://user-images.githubusercontent.com/234708/33901691-86e0540c-df6a-11e7-8730-c3116b07ece1.png)

We need to identify components that are unique to this page and one that can be used in the app.

**Comment by spences10** [comment]
Ok, so here's my attempt at identifying the components here:

Obvious ones first:
* Nav and it's components
* Styled h1 and p's
* Hero - big image

Then:

* Icons - see https://github.com/chingu-voyage3/bears-16/issues/28#issuecomment-351331333 for details
* Bear team logo component - to go in the nav

**Comment by mar-bi** [comment]
I have nothing to add! :clap: :100: 
I like how you name a component **"hero"**. I'd like to use this name for it.

**Comment by spences10** [comment]
Closing this one, all items accounted for on https://github.com/chingu-voyage3/grad.then/issues/21
