### ISSUE TITLE
Break Jobs page into components

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#23]
# discussion piece

![image](https://user-images.githubusercontent.com/234708/33902222-3f2dab08-df6c-11e7-9f64-deb453204cb8.png)

We need to identify components that are unique to this page and one that can be used in the app.

**Comment by spences10** [comment]
![image](https://user-images.githubusercontent.com/234708/33979195-302607ce-e09b-11e7-94ed-4022777a84a1.png)

## Components 

* Nav
* Divider
* Search + Filter
* ??
* ?? 

I don't know what the last two sections are @mar-bi could you identify them for me please?

**Comment by spences10** [comment]
Pagination? > ![image](https://user-images.githubusercontent.com/234708/33984781-b26b1ac0-e0b0-11e7-8c5b-12b9c93bd111.png)

Can you identify this please @mar-bi  > 
![image](https://user-images.githubusercontent.com/234708/33984823-cc212310-e0b0-11e7-9250-7d23767ec76d.png)

**Comment by mar-bi** [comment]
Yes, these 2 boxes are `pagination`.
Then 2 components:
from left to right
  - `extended filter` - many different ways to filter jobs
  - `jobs list` with items describing a job offer

**Comment by spences10** [comment]
super, added to the [list](https://github.com/chingu-voyage3/grad.then/issues/21)

closing this now
