### ISSUE TITLE
Break Events page into components

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#24]
# discussion piece

![image](https://user-images.githubusercontent.com/234708/33902383-be221df4-df6c-11e7-9fee-9b4b12c6b8ef.png)

We need to identify components that are unique to this page and one that can be used in the app.

**Comment by spences10** [comment]
![image](https://user-images.githubusercontent.com/234708/33979398-0fd58494-e09c-11e7-9d3f-aadf2d13f5a9.png)

## Components

* Nav
* Divider
* Search + Filter
* Events Card
* Events container

**Comment by mar-bi** [comment]
Everything is right. :+1:

**Comment by spences10** [comment]
Ok, adding cards container as one item for Stories, Projects, Jobs etc

closing
