### ISSUE TITLE
Break Support page into components

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#26]
# discussion piece

![image](https://user-images.githubusercontent.com/234708/33902492-0f63ad54-df6d-11e7-88c4-457d46e26570.png)

We need to identify components that are unique to this page and one that can be used in the app.

**Comment by spences10** [comment]
![image](https://user-images.githubusercontent.com/234708/33933069-8a7c26c2-dfec-11e7-84ab-ca65ec175263.png)

## Components
* Nav
* Hero??
* Project card
* Projects container
* Featured projects container
* Serarch

**Comment by mar-bi** [comment]
Exactly! :+1: 
Plus:  
1. Divider - gray box with text. It serves to divide a very long page. We have the same box on the `learn` page with some funny numbers and icons. 
*(I think it some kind of fashion now to have such boxes with some funny numbers of users, items, revenues, cups of coffee,...)*
2. 2 lonely black boxes near the `search` box are filters ("latest" and "all" for example)

**Comment by spences10** [comment]
The projects containers could we make a generic 'cards' container??

**Comment by spences10** [comment]
closing now with reference to [this](https://github.com/chingu-voyage3/grad.then/issues/24#issuecomment-351657965)
