### ISSUE TITLE
Break Stories page into components

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#27]
# discussion piece

![image](https://user-images.githubusercontent.com/234708/33902576-556b6472-df6d-11e7-8147-2ba9ac816a10.png)

We need to identify components that are unique to this page and one that can be used in the app.

**Comment by spences10** [comment]
## Components

I've made some presumptions here if you can clarify @mar-bi this will help for the next pages 👍 

Excuse my shaky hand 😸 

![image](https://user-images.githubusercontent.com/234708/33932412-cb542bce-dfea-11e7-879f-8c6a9af07243.png)

So, top is the nav, correct?

So if you can clarify what the other dark boxes are that would be great 💯 

The only thing other than those I can identify would be:

* stories container
* stories card 
* the buttons
* search

**Comment by mar-bi** [comment]
> So, top is the nav, correct?  

Yes, absolutely. Your identification of components is correct.  :+1: :mag: 

Here I try describe the page components from the top to the bottom of the page.
We have:
1. `Header` (grad.then() + navigation menu)
2. `Dashboard` (heading with the name of  the page + some text + a button)
3. `Main`: 
    * nav - a filter for stories ("latest", "oldest", "craziest" :grinning: ) 
    * search box
    * stories container with stories cards
    * pagination (a small black box right down the stories container) - shows pages with arrows
4. `Footer`

Story card contains:
  - image or avatar (dark circle)
  - heading of the story
  - paragraph of story text
  - button

**Comment by spences10** [comment]
Ok, so `StoryCard` will be an issue in it's own right to go into the Components project?

Components project isn't a thing yet, feel free to create it 👍 

we'll get a checklist going on the [main](https://github.com/chingu-voyage3/bears-16/issues/21) ticket for the components identification project 🎉

**Comment by mar-bi** [comment]
Yes, `StoryCard` have to be an independent issue.
**Story Project** have to be created to, and checklist will help to track the identification.

**Comment by spences10** [comment]
closing this now, all items listed on #21
