### ISSUE TITLE
Repo Name Change

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#31]
**Just remembered we can do this**

👍 

![image](https://user-images.githubusercontent.com/234708/33942810-0f822930-e00f-11e7-8b58-5ecb98d78bda.png)

**Comment by mar-bi** [comment]
Cool! :+1: 
We can rename it!

**Comment by spences10** [comment]
`grad-then` or `grad.then` I'm only a little bit nervous about the dot in the repo name, I don't think it's an issue

**Comment by spences10** [comment]
looking at it `grad.then` looks much better

**Comment by mar-bi** [comment]
agree. `grad.then` is much better. Would it (renaming) cause any problem with my local clone? or shall i clone it again?

**Comment by spences10** [comment]
I don't think so
just rename it locally

**Comment by mar-bi** [comment]
ok. let's do it

**Comment by spences10** [comment]
done 🙃 

renamed the repo folder then cd into it did a git pull, all good 👍
