### ISSUE TITLE
Story Card

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#32]
# Story Card - component 

![image](https://user-images.githubusercontent.com/234708/33943755-d983eb22-e011-11e7-85f0-3858bd5a510b.png)

General mockup pictured from the wireframes...

Story card contains:
  - image or avatar (dark circle)
  - heading of the story (2 dark boxes)
  - paragraph of a story text
  - button  

Details [here](https://github.com/chingu-voyage3/bears-16/issues/27#issuecomment-351346815)

**Comment by spences10** [comment]
I'm going to pick this up unless anyone else has a real burning desire to do so.

Let me know, for now though I'm removing you guys 😛 @mar-bi @asanhix  @miljan-fsd

**Comment by mar-bi** [comment]
It's ok! :+1: 
Look forward to see the result! :clap:

**Comment by spences10** [comment]
Needs `Button` adding still Scott 🙃

**Comment by spences10** [comment]
Closed with https://github.com/chingu-voyage3/grad.then/pull/66
