### ISSUE TITLE
Project Card

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage3/grad.then#33]
## Project Card Component
![projectcard](https://user-images.githubusercontent.com/25195616/33945483-d7c7cef0-e027-11e7-9983-c2e17a3f12bb.png)

`Project Card` contains:
   * image
   * heading with the project title
   * paragraph with the project details

**Comment by mar-bi** [comment]
I see that this `ProjectCard` is quite similar with a card from `Events` page.
The main difference is that `EventCard` use a **list** for event details instead of **paragraph**.
I suggest to merge it in one card. Maybe with conditional styling.

**Comment by spences10** [comment]
I'd be interested to see how that is done @mar-bi 

Do you want to update the checklist on the main issue for this and add it to the components project?

**Comment by mar-bi** [comment]
Here is an example how this *"conditional rendering"* can be done.
I added one more card
![cardwithouttitle](https://user-images.githubusercontent.com/25195616/33981475-c0760b7a-e0b5-11e7-8a8f-a2dcc63e94df.png)
and try to get 3 **slightly different cards** from one component.

in `components\ProjectCard.js` 
```
import React from 'react'
```
**Option 1** - through style
Here I simply **hide** a title for a `card`, if it receives a right prop (in my case it is "none"):
```
const ProjectTitle = styled.h3.attrs({
  display: props => props.visibility || "block"
})`
  font-size: 1.2rem;
  text-align: center;
  color: CP.primary.light;
  display: ${props => props.display};
`
``` 
I create `ul` and `p` components
```
const ProjectUl = () => (
  <CardUl>
    <CardLi>25.01.18</CardLi>
    <CardLi>Great Piramids of Giza</CardLi>
    <CardLi>React Developers Summit</CardLi>
  </CardUl>
)

const ProjectP = () => (
  <CardP>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Cumque reprehenderit soluta, dolores aperiam quia, laborum ipsa,
    inventore delectus, necessitatibus voluptates adipisci? 
  </CardP>
)
```
**Option 2** - with ternary operator
I add them to the end of `ProjectCard` component right into a *ternary operator*  
```
const ProjectCard = (props) => (
  <ProjectContainer>
    <ProjectImage src="http://lorempixel.com/400/200" alt="test image" />

    <ProjectTitle visibility={props.title}>Our nice project</ProjectTitle>

    { (props.type === 'event')
      ?<ProjectUl />
      : <ProjectP /> }
  </ProjectContainer>
)
export default ProjectCard
```
Then I handle export-import and call `ProjectCard` from `\pages\index.js` (for this example) passing props to it:

in `\pages\index.js`
```
const IndexPage = () => (
  <div>
    <StyledH1>Hi people</StyledH1>
    <StyledP>{faker.lorem.paragraph()}</StyledP>
    <p>Now go build something great.</p>

    <StyledP>Like these 3 cards</StyledP>
    <CardContainer>
      <ProjectCard type="project" />
      <ProjectCard type="event" />
      <ProjectCard type="project" title="none" />
    </CardContainer>

    <Link to="/page-2/">Go to page 2</Link>

  </div>
)
```
I skipped some styling details in order not to make this post clumpy. (I made a **long-read** instead :laughing: )

That is how the **main page** looks like: 
![mainpage](https://user-images.githubusercontent.com/25195616/33981595-2eee8f28-e0b6-11e7-975d-cc611aa43468.png)

I expect with some improvements we can build a full bunch of cards following this example. :hammer:

**Comment by mar-bi** [comment]
I like it, I take it. :yum:
