### ISSUE TITLE
how to Mobile Responsive

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#35]
I know it's early days with this but I'm wondering how we make the nav mobile responsive, it sort of works

![grad then responsive](https://user-images.githubusercontent.com/234708/33984144-80aea7a6-e0ae-11e7-9bc6-6a6a7a470d9d.gif)

@mar-bi is this something you have done before?

**Comment by mar-bi** [comment]
My answer is "yes". I have done it before.
`@media` will save us. :smile: 
**media queries**, I mean.
Till now we didn't tell the browser how to lay out our content for small screens.

**Comment by spences10** [comment]
Ok, another lesson coming up 🤓

**Comment by mar-bi** [comment]
I will. :nerd_face: 
Just to illustrate that it is possible.
I have made the 3 `Cards` to line up differently on screens with `max-width < 600px`

![3cards](https://user-images.githubusercontent.com/25195616/33985958-c719106c-e0c4-11e7-8026-a41407445680.png)

with this *piece of code*:

```
const CardContainer = styled.div`
  max-width: 700px;
  padding: 0.5rem;
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  grid-template-rows: auto;
  grid-column-gap: 1rem;
  margin-bottom: 1rem;

  @media (max-width: 700px) {
       background: palevioletred;
       grid-template-columns: repeat(2, 1fr);
}`
```  
It's just a simple example of the power of **CSS grid** and `@media`. :upside_down_face: 

However, this subject will need a **separate project**. 
I really prefer (it is not right, I know) to do it when a **large screen** layout is complete. 
Sorry, I use to brake the `mobile-first` paradigm. :upside_down_face:
