### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage3/grad.then#37]
There is 1 type of buttons* which is presented in 2 sizes: 

  -**big**
![button](https://user-images.githubusercontent.com/25195616/33987021-1e41aebe-e0c8-11e7-9508-85f1d6a19e10.png)

  -**small**
![button_small](https://user-images.githubusercontent.com/25195616/33987044-2d098d40-e0c8-11e7-9f72-6f853208a2c3.png)

All buttons share the same `css` features: 
  - outlined button - just colored borders
  - no background
  - button text is UPPERCASE,
  - border size : 1 or 2 px ???
 
---
*we discuss here **flat buttons** only. **Icon buttons** have a separate issue.  (I hope :upside_down_face: )

**Comment by spences10** [comment]
mmmmmmm, buttons

**Comment by spences10** [comment]
Taking this one 👍

**Comment by spences10** [comment]
Taking this one 👍

**Comment by spences10** [comment]
Closed with #67
