### ISSUE TITLE
Hero Component

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage3/grad.then#39]
`Hero` component
1. `Main` page `Hero`
![hero](https://user-images.githubusercontent.com/25195616/34014655-a73a5d68-e124-11e7-948e-d6c86c4dbe7e.png)

consists of:
  - container - takes 10 columns of the page and contains: 
  - heading (`<h1>`  or `<h2>`)
  - list of items
  - attractive image as **css background**

2. all other pages `Hero` without `Button`
![hero2](https://user-images.githubusercontent.com/25195616/34045268-cde8a62c-e1b0-11e7-917b-c8cec13282fc.png)

3. all other pages `Hero` with `Button`
![hero2withbutton](https://user-images.githubusercontent.com/25195616/34045305-0550b172-e1b1-11e7-84b5-7e3444c6efb3.png)

 2 last `Heroes` contain:
  - container - takes 10 columns of the page and contains: 
  - heading (`<h1>`  or `<h2>`)
  - `<p>`
  - `Button` (`Hero3` only)
  - **css background** use one color from **ColorPalette**

**Comment by mar-bi** [comment]
I'd like to pick up `Hero`, however it have to be built after `Buttons`. :pause_button:

**Comment by spences10** [comment]
![giphy 1](https://user-images.githubusercontent.com/234708/34071034-c8ed055c-e267-11e7-9a6c-f503a2aad0b3.gif)

**Comment by mar-bi** [comment]
Ok. I take it :handbag:

**Comment by mar-bi** [comment]
closed with #91
