### ISSUE TITLE
git branches

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#41]
I'm thinking now we're going to quite possibly be developing on four different branches we should maybe consider making a `development` branch where our `dev/#/feature` get's merged into first before being moved up to master.

What's everyone's thoughts on this way of managing the changes?

**Comment by mar-bi** [comment]
I totally agree with your arguments @spences10 . :+1: 
We need to create the `development` branch.

**Comment by spences10** [comment]
Ok, I think I need to update the README.md with some relevant information for this

As a reference 🤔

**Comment by mar-bi** [comment]
>Ok, I think I need to update the README.md with some relevant information for this

Right. :+1:  
Besides, I think we need provide a small guide how to use branches, make poll requests. Some kind of basic contribution etiquette. :question:

**Comment by spences10** [comment]
Ok, see https://github.com/chingu-voyage3/grad.then/issues/43

**Comment by mar-bi** [comment]
@spences10, 
I think it would be better if we don't `push` own branch directly to `development `.
I'd like to enforce code reviews at the `development` branch first.
It would be no needs to update `master` after every single `component` addition.
What do you think?

**Comment by spences10** [comment]
So push `dev/spences10/32/story-card` to `development` then from `development` to `master`?

I'm beginning to think maybe we use Travis or some form of CI @mar-bi?

**Comment by spences10** [comment]
closed with https://github.com/chingu-voyage3/grad.then/pull/50
