### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#42]
It's a way off yet but it has been mentioned so let's have it as a discussion point.

Let me know your thoughts on this.

Personally, I ❤️  the `now` CLI from Zeit - I was reliably informed yesterday that for OSS you can have teams, `now` CLI has great configuration options and also deployments can be made, then tested then promoted up to production by re aliasing the link.

Other options mentioned were:

* [Netlify.com](https://www.netlify.com/)
* [surge.sh/](https://surge.sh/)
* Heroku
* GitHub pages

**Comment by mar-bi** [comment]
I have used *Heroku*, *GitHub Pages* and *Glitch*.
You suggest `now`.  I agree to give it a try

**Comment by asanhix** [comment]
#82 will close this right?

**Comment by spences10** [comment]
It could, but I'd prefer to have everyone's opinion on how we handle deployment

Currently it's not great

**Comment by spences10** [comment]
I think that we're all happy with GitHub pages for deployment on this now, right?

GH Pages was the only solution we could all use with the least fuss, we could use Travis CI to automate the build of the site once it is moved from `development` to `master` as well

**Comment by mar-bi** [comment]
I'm happy with **gh-pages** and agree for Travis CI automation :upside_down_face:

**Comment by spences10** [comment]
Need to add a GitHub token for the pipeline, I'll fix this later this morning.
