### ISSUE TITLE
README.md information

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#43]
## Info to be added to the README.md

- [x] Config information [how it works/is put together]
- [x] Deployment information
- [x] Milestones
- [x] Projects
- [x] How to use - `npm init` etc
- [x] Git branch information
- [x] How to branch
- [x] Detail libraries used
- [x] Authors
- [x] Licence

Anything else need adding?

**Comment by mar-bi** [comment]
I would add info about projects. ( If I want to build a button, where to find its description.)
And maybe milestones with dates.  To have in front of the eyes.

**Comment by spences10** [comment]
OMG YES!

I have only added vague dates and milestones but we need to discuss these!!

**Comment by asanhix** [comment]
maybe we can add contributing section to readme.md

**Comment by spences10** [comment]
Absolutely, but currently, it's just us 👌
