### ISSUE TITLE
Icons Component

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#47]
# Icon Component

Icon:

From this great post https://medium.com/@david.gilbertson/icons-as-react-components-de3e33cb8792

Create a `const.js || constants.js` file with all the SVG icons
Create a `icons.js` file which returns the `Icon` component

**Comment by asanhix** [comment]
For the most part maybe we can use unicode chars they have enormous icon like characters maybe we do not need to use any library at all 🐻
https://unicode-table.com/en/1F43B/

**Comment by mar-bi** [comment]
I prefer to use **SVG icons**. :upside_down_face: 
They are scalable and text-based. 
You can easy style them using **CSS** and store with your constants. 
There are many good and free libraries of **SVG** icons, and we can pick up just what we want.

**Comment by spences10** [comment]
☝️  this
