### ISSUE TITLE
check your origin URL

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#49]
check that the repo name change doesn't affect you

```
git remote -v 
```

If you get:

```
origin  git@github.com:chingu-voyage3/bears-16.git (fetch)
origin  git@github.com:chingu-voyage3/bears-16.git (push)
```

then change it with:

```
git remote set-url origin git@github.com:chingu-voyage3/grad.then.git
```

check again to verify with `git remote -v` you should have

```
origin  git@github.com:chingu-voyage3/grad.then.git (fetch)
origin  git@github.com:chingu-voyage3/grad.then.git (push)
```

Or the https equivalent 😉

**Comment by mar-bi** [comment]
Thank you @spences10 for this guideline. :+1: 
I changed the `remote` according these instructions.

**Comment by spences10** [comment]
it was only when I pushed a new branch that I saw the prompt, it was a deprecation warning so it would probably have worked for a while longer. 🤷‍♂️

**Comment by mar-bi** [comment]
It is safer to change the `remote`. 
I think we have to keep this branch active, until we are sure that all clones has access to the `origin`.

**Comment by spences10** [comment]
I'm not when @miljan-fsd and @asanhix cloned, if it was after the name change then I guess there not going to be any issues

**Comment by asanhix** [comment]
Checked and it is up to date with the current origin. :) Thank you.

**Comment by spences10** [comment]
Ok, so if we have @miljan-fsd sign off then we can close? 🤔

**Comment by mar-bi** [comment]
Yes. We can close it.

**Comment by asanhix** [comment]
Yes I agree we can close.
