### ISSUE TITLE
Bears Team Logo Component

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#51]
## Logo 
![bear](https://user-images.githubusercontent.com/234708/34014462-16d40974-e113-11e7-9228-ffdf2b552db6.png)

Light Bear SVG:
'M490.182,135.355c14.07-14.07,21.819-32.776,21.819-52.673c0-19.898-7.749-38.604-21.819-52.673 c-29.043-29.045-76.304-29.045-105.347,0l-15.108,15.108c-34.72-19.154-73.783-29.222-113.726-29.222 s-79.006,10.069-113.726,29.222l-15.108-15.108c-29.044-29.046-76.303-29.046-105.347,0C7.749,44.077,0,62.783,0,82.681 c0,19.897,7.749,38.603,21.819,52.673l19.277,19.277c-13.816,30.49-20.812,63.061-20.812,96.98v252.166h471.436V251.611 c0-33.918-6.995-66.489-20.812-96.98L490.182,135.355z M438.976,158.419c14.811,29.02,22.323,60.374,22.323,93.192v221.746H50.702 V251.611c0-32.817,7.511-64.172,22.323-93.192l5.027-9.85l-34.725-34.724c-8.324-8.325-12.908-19.392-12.908-31.165 c0-11.772,4.584-22.84,12.908-31.164C51.652,43.194,62.72,38.61,74.491,38.61s22.839,4.584,31.164,12.908l31.942,31.943 l10.249-6.366c32.419-20.137,69.817-30.78,108.152-30.78c38.336,0,75.733,10.644,108.152,30.78l10.249,6.366l31.942-31.943 c8.325-8.324,19.392-12.908,31.164-12.908s22.839,4.584,31.164,12.908c8.324,8.324,12.908,19.391,12.908,31.164 c0,11.771-4.584,22.839-12.908,31.164l-34.724,34.724L438.976,158.419z M256,201.429c-62.046,0-112.526,50.479-112.526,112.526S193.953,426.483,256,426.483s112.526-50.479,112.526-112.527 C368.526,251.908,318.047,201.429,256,201.429z M271.21,394.627v-89.664h25.82v-30.419h-82.059v30.419h25.82v89.664 c-38.028-7.156-66.897-40.596-66.897-80.672c0-45.273,36.833-82.107,82.107-82.107c45.274,0,82.107,36.833,82.107,82.107 C338.107,354.031,309.239,387.472,271.21,394.627z M353.331,155.303c-13.347,0-24.206,10.859-24.206,24.206c0,13.348,10.859,24.207,24.206,24.207 c13.347,0,24.206-10.859,24.206-24.207C377.537,166.162,366.678,155.303,353.331,155.303z M158.669,155.303c-13.347,0-24.206,10.859-24.206,24.206c0,13.348,10.859,24.207,24.206,24.207 c13.347,0,24.206-10.859,24.206-24.207C182.875,166.162,172.017,155.303,158.669,155.303z M450.133,70.054c-3.372-3.371-7.854-5.228-12.624-5.228c-4.769,0-9.253,1.857-12.625,5.229l-25.37,25.371l10.162,10.746 c1.123,1.189,2.24,2.4,3.349,3.629l10.726,11.888l26.382-26.383C457.092,88.348,457.094,77.022,450.133,70.054z M87.09,70.027c-3.372-3.354-7.846-5.201-12.598-5.201c-4.769,0-9.253,1.857-12.624,5.229 c-6.959,6.958-6.962,18.284-0.006,25.246l26.388,26.386L98.975,109.8c1.109-1.229,2.225-2.44,3.349-3.629l10.161-10.745 L87.09,70.027z'

![bear-dark](https://user-images.githubusercontent.com/234708/34014468-1a22bc74-e113-11e7-9bdb-cc4364be0eb1.png)

Dark Bear SVG:
'M490.182,135.355c14.07-14.07,21.819-32.776,21.819-52.673c0-19.898-7.749-38.604-21.819-52.673 c-29.043-29.045-76.304-29.045-105.347,0l-15.108,15.108c-34.72-19.154-73.783-29.222-113.726-29.222 s-79.006,10.069-113.726,29.222l-15.108-15.108c-29.044-29.046-76.303-29.046-105.347,0C7.749,44.077,0,62.783,0,82.681 c0,19.897,7.749,38.603,21.819,52.673l19.277,19.277c-13.816,30.49-20.812,63.061-20.812,96.98v252.166h471.436V251.611 c0-33.918-6.995-66.489-20.812-96.98L490.182,135.355z M90.435,93.883c-1.069,1.13-2.131,2.281-3.185,3.451l-17.88,19.815 l-14.68-14.676c-10.905-10.918-10.903-28.674,0.006-39.586c5.288-5.288,12.318-8.2,19.795-8.2c7.449,0,14.461,2.894,19.747,8.149 l13.13,13.137L90.435,93.883z M134.463,179.51c0-13.347,10.859-24.206,24.206-24.206s24.206,10.859,24.206,24.206 c0,13.348-10.859,24.207-24.206,24.207S134.463,192.858,134.463,179.51z M271.21,430.211V312.646h29.983v-30.419h-90.387v30.419 h29.983v117.565c-51.997-7.387-91.985-52.078-91.985-106.115c0-59.202,47.993-107.195,107.195-107.195 s107.195,47.993,107.195,107.195C363.194,378.133,323.207,422.824,271.21,430.211z M353.331,203.717 c-13.347,0-24.206-10.859-24.206-24.207c0-13.347,10.859-24.206,24.206-24.206c13.347,0,24.206,10.859,24.206,24.206 C377.537,192.858,366.678,203.717,353.331,203.717z M457.309,102.472l-14.68,14.676l-17.879-19.815 c-1.054-1.169-2.116-2.321-3.185-3.451l-16.933-17.91l13.13-13.137c5.286-5.255,12.299-8.149,19.747-8.149 c7.477,0,14.508,2.912,19.795,8.2C468.212,73.798,468.214,91.555,457.309,102.472z'

**Comment by mar-bi** [comment]
Cool! 
Pure SVG! I told you that I like these cute bears. After I saw the `path`, I like them even more: :smile:

**Comment by mar-bi** [comment]
I'd like to pick up this. 
It will join nicely my collection of SVGs and my `navs`.  :crown:
Hope, nobody has objections. :smiley:

**Comment by mar-bi** [comment]
I started `BearsTeam` Component

![image](https://user-images.githubusercontent.com/25195616/34071250-1de5b086-e27c-11e7-94fc-39ba6f5275ad.png)

I'd like to wrap it into a link, so it will point out to our repo (or any other location, please suggest).

@spences10 , @asanhix , @miljan-fsd 
Please also suggest how to improve text, alignment of text and icon, hover color, and any ideas you like to add.
Thank you :four_leaf_clover:

**Comment by spences10** [comment]
Hmm, yeah, the Repo or the [Authors][auth] section on the [README.md][rm]

[auth]: https://github.com/chingu-voyage3/grad.then#authors
[rm]: https://github.com/chingu-voyage3/grad.then#gradthen

**Comment by mar-bi** [comment]
*Authors* is better, I guess.

**Comment by spences10** [comment]
I ❤️ the way this look by the way 🥇
