### ISSUE TITLE
Search-and-Filter Component

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage3/grad.then#52]
Search-and-Filter Component
![search-filter](https://user-images.githubusercontent.com/25195616/34015302-b0137012-e126-11e7-8e44-986c55befbf1.png)

contains:
  - container
  - list of links (`filter`)
  - input (`search`) without a search button

**Comment by asanhix** [comment]
@mar-bi  maybe we can break this in two sub components what do you think?

**Comment by spences10** [comment]
What are the sub components?

**Comment by asanhix** [comment]
* search bar
* filter tags
maybe?

**Comment by mar-bi** [comment]
I'd prefer to have it like 1 component because of the usage pattern.
This `filter` has always `search` companion. :dolls:

So it can be
```
<div>
  <Filter>
    <a></a> // custom number of <a>
    <a></a>
  </Filter>
  <Search />
</div>
```
The number of `<a>` can be received via props. Then we need to build all `<a>` using the `map` function.
