### ISSUE TITLE
Pagination Component

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage3/grad.then#54]
**Pagination** is a few clickable digits down a list
Its role is to bring the next `n` items of the list.

![pagination](https://user-images.githubusercontent.com/25195616/34037167-63ee4b8e-e190-11e7-8aff-d648f8747524.png)

This is a nice example of `Pagination`. (thanks *Github*) :upside_down_face: 
![paginationexample](https://user-images.githubusercontent.com/25195616/34038558-774ca43c-e195-11e7-810a-a6fb04adcfc6.png)

The `Pagination` component contains:
  - container
  - 2 inline links (with symbols like "<<" and ">>")

**Comment by spences10** [comment]
I'll take this 👍

**Comment by mar-bi** [comment]
closed with #80
