### ISSUE TITLE
Jobs List Component

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage3/grad.then#56]
## Jobs List Component

1. thick boxes (rows) - `jobs` page
![jobslist](https://user-images.githubusercontent.com/25195616/34044920-9e31f588-e1af-11e7-8ce6-eae3c6f43948.png)

2. thin boxes (rows) - `learn` page
![learnlist](https://user-images.githubusercontent.com/25195616/34044955-c21403ec-e1af-11e7-9a66-534f32a74e3b.png)

Contains:
  - container
  - a number of `div's` with data (about jobs and courses)

**Comment by spences10** [comment]
Should this be:

For `Jobs` a `<h2>` for the headline and a `<p>`?

For `Learn` just the `<h2>`

I presume it will be two props, header and paragraph??

**Comment by mar-bi** [comment]
Yes. For `Learn` could be `<h2>` and `<ul>` with dates or details.
And 2 props.

**Comment by spences10** [comment]
Ok, I'll take this one too 😄
