### ISSUE TITLE
Prettier pre-commit

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#59]
# Prettier all the things

Not sure if any of you guys have noticed that Prettier come installed with the Gatsby starter we're using, if you're not familiar with Prettier it's an opinionated code formatter I run it on the `development` branch with `npm run format` and got a few changes, 😬 

![image](https://user-images.githubusercontent.com/234708/34054230-dd15ac24-e1c1-11e7-8267-ee8e51142bb5.png)

I suggest that we use a `pre-commit` hook to make sure the code is formatted before saving, [this][guide] looks like it could be quite handy, I'm going to try it out and submit a PR on the back of this issue.

[guide]: https://gist.github.com/primaryobjects/9ab8d2346aa58ef6959ad357bb835963

Thanks.

**Comment by mar-bi** [comment]
I noticed this package in `package.json`.
Now I know what will consume my lovely semicolons. :upside_down_face: 
Great idea, let's make code prettier. :+1:
