### ISSUE TITLE
Use styled-components <ThemeProvider>

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#69]
# Discuss with me 😄 

I'd like us to consider using the `[<ThemeProvider>]` [wrapper][theme] in styled components 

It provides theming to all components underneath it, it could be handy for things like this [function theme][func-theme] for inverting colours.

This example would then need ` theme={theme}` passed instead of defining the colours via props.

![image](https://user-images.githubusercontent.com/234708/34077120-c3829f88-e2f2-11e7-9cf1-92f02f136246.png)

[theme]: https://www.styled-components.com/docs/advanced#theming
[func-theme]:https://www.styled-components.com/docs/advanced#function-themes

**Comment by asanhix** [comment]
Would be nice addition I think because no redundant color definition only one place to change color variables via theme.

**Comment by mar-bi** [comment]
I likes the idea of `theming`, however I don't quite understand how the file structure is going to be organized. 
We are going to add `theme` to `globalStyle` and then import it, right? :thinking: 
After that we can use cool things like **function theme**.

**Comment by spences10** [comment]
The root component will need to be wrapped in the <ThemeProvider> then things like brand colour will be available...

So I think if we add the following:

**`src/theme/globalStyle.js`:**
```js
...
import styled, { ThemeProvider, injectGlobal } from 'styled-components'

injectGlobal`
...
`

// define the theme
const theme = {
  primary: {
    dark: '#453463',
    light: '#755f9f'
  }
}
...
```

Ah, I see the problem here:

**`src\layouts\index.js`:**
```js
import styled, { ThemeProvider, injectGlobal } from 'styled-components'

// not sure if we need `injectGlobal`
...
```

Let me come back to this, I'm going to Google around see if I can find some examples with Gatsby

**Comment by mar-bi** [comment]
@spences10 , have you taken this issue?
It will be followed by an issue with changes to existing components.
I'd like to help with them. :construction_worker_man:

**Comment by spences10** [comment]
I have @mar-bi yes, working on it now

It's going to change all components that use the `ColourPallette` what is it you'd like to help with?

I can push what I have done so far so you can compare and take a look at what's happened so far??

**Comment by mar-bi** [comment]
I expect there would be lots of changes in components to replace current `ColorPalette`.
If you are ready, you can push it and we will test it. :upside_down_face:
