### ISSUE TITLE
Button text not upper case

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#76]
Someone didn't follow the spec for the `Button` component 

###### that someone is me 🙃 

Will need to add...

```css
text-transform: uppercase;
```

to the `Button` component

I'll pick this up unless someone wants to take a look at it 👍

**Comment by asanhix** [comment]
Will add that css rule
I am on it :smile:

**Comment by mar-bi** [comment]
This is considered as  a **css best practice** to make `uppercase` in **CSS** not **HTML**.:ok_hand:

**Comment by asanhix** [comment]
:+1:

**Comment by mar-bi** [comment]
closed by #78
