### ISSUE TITLE
make-main-page

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage3/grad.then#8]

**Comment by spences10** [comment]
Ok, let's talk components for this, I'm guessing as we're using `styled-components` 💅  we can use a global style theme where we can pull our styled compoenents from ??

So in the `main-page` there's going to be a `h1` will we have the same styled `h1` throughout the app?

I'm guessing, yes?

So, maybe when putting together this page we also consider things like `h1`-`h6` and how they're styled along with `p` and `div`'s??

Consider this:

```text
bears-16/
├─ .cache/
├─ node_modules/
├─ public/
├─ src/
│  └─theme/globalStyle.js
├─ .gitignore
│...
```

**`globalStyle.js`**
```js
import styled, { injectGlobal } from 'styled-components'

injectGlobal`
  @import url('https://fonts.googleapis.com/css?family=Open+Sans|Roboto');

  body {
    padding: 0;
    margin: 0;
    font-family: Roboto, Arial, sans-serif;
    font-size: 20px;
    line-height: 1.3125;
  }

  a {
    text-decoration: none;
  }

  ul {
    margin: 0 auto;
  }

  @media screen and (min-width: 360px) {
    html {
      font-size: 15px;
    }
  }

  @media screen and (min-width: 600px) {
    html {
      font-size: 16px;
    }
  }
`

export const StyledH1 = styled.h1`
  padding: 1.75rem;
  margin: 0.5rem;
`

export const StyledP = styled.p`
  padding: 1.75rem;
  margin: 0.5rem;
`

export const StyledUl = styled.ul`
  padding: 1.75rem;
  margin: 0.5rem;
`

export const StyledLi = styled.li`
  padding: 1.75rem;
  margin: 0.5rem;
  text-decoration: none;
`

export const StyledA = styled.a`
  padding: 1.75rem;
  margin: 0.5rem;
`
```

Then to use it in our code:

```js
import { StyledH1, StyledP } from '../theme/globalStyle'

class About extends React.Component {
  render() {
    return (
      <Body>
        <StyledH1>grad.tehn()</StyledH1>
        <StyledP>Do stuff after graduating</StyledP>
      </Body>
    )
  }
}

export default About
```

**Comment by mar-bi** [comment]
You are right. I was thinking to have a global `.css` file for the app. I agree and understand how to use it.
Will you add it?

**Comment by mar-bi** [comment]
There is a small issue with **CSS** - an existing CSS file in `\layouts` folder. It takes a precedence if its usage is not commented out.
Basically, this file contains almost a **reset** together with **vendor prefixes**.
We can delete it in future, I think.

**Comment by spences10** [comment]
Are you talking about https://github.com/chingu-voyage3/bears-16/issues/14 here @mar-bi?

**Comment by mar-bi** [comment]
> Are you talking about #14 here @mar-bi?
I'm talking about an interaction between 2 style-sheets. Should I move my comments to #14 ?

**Comment by spences10** [comment]
@mar-bi let's make another issue for it as I've deleted the branch now and it is separate from #14
