### ISSUE TITLE
Nav enhancement

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage3/grad.then#98]
We'd like to see the app `Nav` perfect and shiny. :sun_with_face: :full_moon_with_face: 

Here we add and discuss ideas of its enhancement. :prince:  

**Current ideas**
  - `outline:none;` for buttons and links - get rid of **dotted rectangle** around a link when it is clicked.
(Could we do this via `globalStyle.js`???)
  -  "ActivePage" highlight for Links (in `Header`, `Footer` or both???).   
  -  fixed `Header`and `Footer` - don't move with scroll

**Comment by miljan-fsd** [comment]
Invert colors, **purple** for background, **white** for text?

**Comment by mar-bi** [comment]
>Invert colors, purple for background, white for text?

This is for `ActiveLink`, right?

**Comment by miljan-fsd** [comment]
Yes. Do you have any other suggestions?

**Comment by mar-bi** [comment]
Now I'm taking about `Header`.
The background is white. `ActiveLink` should have a colour that is visible on the white background.
Or do you want to draw a **violet** button with **white** text around the `ActiveLink`?

**Comment by mar-bi** [comment]
![screenshot-2017-12-19 grad then](https://user-images.githubusercontent.com/25195616/34161475-75825c40-e4d9-11e7-8ef9-6b2ff55de177.png)

**Comment by miljan-fsd** [comment]
It would be great if the top and bottom edges of `ActiveLink` match the header edges.

**Comment by miljan-fsd** [comment]
My Prepositions:
- Fixed `Header` only
- ActivePage in `Header` only

**Comment by mar-bi** [comment]
1. Full edges
![screenshot-2017-12-19 grad then 3](https://user-images.githubusercontent.com/25195616/34162509-ab1c9ea8-e4dc-11e7-92ec-3a406e9fe7e2.png)


2. Another idea - no `bg` just `outline`

![screenshot-2017-12-19 grad then 2](https://user-images.githubusercontent.com/25195616/34162479-880455f0-e4dc-11e7-8bf8-49e3cd250e25.png)

**Comment by miljan-fsd** [comment]
We can go with second option. :100:

**Comment by spences10** [comment]
Really small detail but can we transform from square edges to the rounded ones on hover too?

With a half second display?

**Comment by spences10** [comment]
I'd like to take this 💪

**Comment by mar-bi** [comment]
You are welcome to take it, @spences10 

I want to add some note that you might find useful. It's about **ActivePage** link.
There is a few special attrs for **Gatsby Link** which can help you.
>You can set the **activeStyle** or **activeClassName** prop to add styling attributes to the rendered element when it matches the current URL 

from [Gatsby Link](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-link)

*This code is from my draft for presentation purpose*
The red outlined link in example I did like this:
```jsx
   <NavLink to="/support" data-header={props.header}
        activeStyle={activeLink2}>
        support
   </NavLink>
```
constant with style
```js
const activeLink2 = {
  "border": `2px solid ${CP.secondary.red}`,
  "border-radius": "5px",
  "color": CP.secondary.red,
  "padding": "0.4rem",
}
```
This is not the only way to do this issue. :upside_down_face: 
Feel free to upgrade `Nav` the way you prefer. :ok_hand:

**Comment by spences10** [comment]
@mar-bi I have tried several combinations for passing `props` and none of them are applied on the `activeStyle`

Tried, this:
```js
const ActiveLink = NavLink.extend`
  color: ${props => props.theme.secondary.red};
`

const PageNav = props => (
  <NavMenu>
    <NavItem data-header={props.header}>
      <NavLink to="/jobs" data-header={props.header} activeStyle={ActiveLink}>
        jobs
      </NavLink>
...
```
And this:
```js
const ActiveLink = {
  color: props => props.theme.secondary.red
}
```
Passing the actual value works though: 🙃 
```js
const ActiveLink = {
  color: 'red'
}
```

**Comment by mar-bi** [comment]
I guess we could use `activeClassName` attr for styling instead of `activeStyle`
**Idea**
add an extra class to `NavLink` then pass it to `activeClassName` 
```js 
const NavLink = Link.extend`
  ... // style of navlink
  &.activeLink {
    color: ${props => props.theme.secondary.red};
  }
```
then 
```jsx
const PageNav = props => (
  <NavMenu>
    <NavItem data-header={props.header}>
      <NavLink to="/jobs" data-header={props.header} activeClassName="activeLink">
        jobs
      </NavLink>
...
 ```
It might work (it depends if  *activeLink* class can be found in a pool of fancy classnames of `styled-components`). :upside_down_face: 
I haven't tested this idea yet.

**Comment by spences10** [comment]
@mar-bi you're the best 👌 

That did it 💯 awesome!!

![grad then](https://user-images.githubusercontent.com/234708/34289353-109b0882-e6ea-11e7-99af-b830c45495dd.gif)

**Comment by mar-bi** [comment]
Wow! That's perfect !!! :1st_place_medal:
